services:
  frontend:
    build: ./frontend
    depends_on:
      - backend
    restart: always
    container_name: jw-frontend
    hostname: frontend
    environment:
      - NODE_ENV=production
      - BACKEND=http://backend
      - NEXT_PUBLIC_BACKEND_API=/api
      - PORT=80
    networks:
      - website

  backend:
    build: ./backend
    depends_on:
      - db
    restart: always
    container_name: jw-backend
    hostname: backend
    environment:
      - DATABASE_URL=mysql://root@db:3306/website
      - FRONTEND=http://frontend
      - PRODUCTION=true
      - PORT=80
    networks:
      - website

  db:
    image: mysql
    container_name: jw-db
    hostname: db
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=website
    networks:
      - website
    volumes:
      - mysql:/var/lib/mysql

  nginx:
    image: nginx:latest
    restart: always
    container_name: jw-nginx
    networks:
      - website
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

networks:
  website:
volumes:
  mysql:
