services:
  app:
    build: ./app
    depends_on:
      - db
    container_name: jw-app
    hostname: app
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://app:${DB_PASSWORD}@db/postgres
      - PORT=80
    networks:
      - website
    ports:
      - "80:80"

  db:
    image: postgres:latest
    container_name: jw-db
    hostname: db
    restart: unless-stopped
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - POSTGRES_PASSWORD=${SUPERUSER_PASSWORD}
    networks:
      - website
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init.sh:/docker-entrypoint-initdb.d/init.sh

networks:
  website:
volumes:
  postgres-data:
