[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.20", features = ["macros", "ws"] }
axum-sessions = "0.5.0"
bcrypt = "0.15.0"
chrono = { version = "0.4.26", features = ["serde"] }
rand = "0.8.5"
regex = "1.9.3"
reqwest = { version = "0.11.18", features = ["json"] }
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.105"
sqlx = { version = "0.7.1", features = ["runtime-tokio", "postgres", "chrono"] }
tokio = { version = "1.32.0", features = ["full"] }
tower-http = { version = "0.4.3", features = ["trace", "cors"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
markdown = "1.0.0-alpha.12"
lazy_static = "1.4.0"
dotenvy = "0.15.7"
hmac = "0.12.1"
sha2 = "0.10.7"
hex = "0.4.3"
aide = { version = "0.12.0", features = ["axum", "axum-ws"] }
schemars = { version = "0.8.15", features = ["chrono"] }
futures = "0.3.29"
