CREATE TABLE IF NOT EXISTS post_redirects (
    id SERIAL PRIMARY KEY,
    slug VARCHAR(255) NOT NULL UNIQUE,
    post_id INT NOT NULL REFERENCES posts(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS folder_redirects (
    id SERIAL PRIMARY KEY,
    slug VARCHAR(255) NOT NULL UNIQUE,
    folder_id INT NOT NULL REFERENCES folders(id) ON DELETE CASCADE
);