CREATE TABLE IF NOT EXISTS folders (
    id SERIAL PRIMARY KEY,
    parent INT REFERENCES folders(id) ON DELETE CASCADE,
    slug VARCHAR(255) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    img VARCHAR(255) NOT NULL,
    timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE
    posts
ADD
    COLUMN folder INT NOT NULL REFERENCES folders(id) ON DELETE CASCADE;