name: Purge Cloudflare Cache
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 3 minutes
        run: sleep 180
        shell: bash
      - name: Purge cache
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
